apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: default
data:
  NEW_FEATURE: "true"

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spinnaker-demo
  namespace: default
  labels:
    source: demo
    stack: frontend
    app: test
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service spinnaker-demo"]'
spec:
  replicas: 3
  selector:
    matchLabels:
      source: demo
      app: test
  template:
    metadata:
      labels:
        source: demo
        app: test
    spec:
      containers:
      - name: primary
        image: index.docker.io/lwander/spin-kub-v2-demo
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: default
spec:
  selector:
    source: demo
    app: test
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
